# SPDX-FileCopyrightText: Copyright (c) 2025 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

###########################################################################
# Box on Plane Example - Multi-Solver Comparison
###########################################################################

import dataclasses
import os

import numpy as np
import warp as wp

import newton
import newton.examples

# from newton._src.solvers.kamino._src.metrics import SolutionMetricsNewton, SolutionMetricsLogger
from newton._src.solvers.kamino._src.utils import logger as msg
from newton.tests import get_kamino_assets_directory

np.set_printoptions(linewidth=20000, precision=6, threshold=10000, suppress=True)

FORCE_START_TIME = 1.0
FORCE_END_TIME = 5.0
MAX_FORCE = 1.5


###
# Classes
###


@dataclasses.dataclass
class SolverSetup:
    # Required inputs
    name: str
    builder: newton.ModelBuilder
    model: newton.Model
    solver: newton.solvers.SolverBase

    # Generated by the model
    state_0: newton.State | None = None
    state_1: newton.State | None = None
    control: newton.Control | None = None
    contacts: newton.Contacts | None = None

    # Time
    time: wp.array | None = None

    # metrics: SolutionMetricsNewton | None = None
    # logger: SolutionMetricsLogger | None = None

    def __post_init__(self):
        self._ref_state = self.model.state()  # Origin state to reset to
        self.state_0 = self.model.state()
        self.state_1 = self.model.state()

        # For Kamino: "reset" the states to populate Kamino-specific arrays (to not break state.assign())
        if hasattr(self.solver, "reset"):
            self.solver.reset(self._ref_state)
            self.solver.reset(self.state_0)
            self.solver.reset(self.state_1)
        self.state_0.assign(self._ref_state)
        self.state_1.assign(self._ref_state)

        self.control = self.model.control()
        self.contacts = self.model.contacts()
        self.time = wp.zeros(dtype=wp.float32, shape=1, device=self.model.device)

    def step(self, state_in: newton.State, sim_dt: float):
        self.model.collide(state_in, self.contacts)
        self.solver.step(state_in, self.state_1, self.control, self.contacts, sim_dt)
        # Pull per-contact forces back into self.contacts.force (when allocated) so
        # the viewer's "Show Contacts -> Forces" / "Modes" layers have data to draw.
        self.solver.update_contacts(self.contacts, self.state_1)
        # self.metrics.evaluate(self.state_1, self.state_0, self.control, self.contacts)
        # self.logger.log()
        wp.launch(_step_time, dim=1, inputs=[sim_dt, self.time])

    def reset(self):
        self.state_0.assign(self._ref_state)
        self.state_1.assign(self._ref_state)
        self.control.clear()
        self.contacts.clear()
        self.time.zero_()
        if hasattr(self.solver, "reset"):
            self.solver.reset(self.state_0)

    def render(self, viewer: newton.viewer.ViewerBase):
        viewer.log_state(self.state_0)
        viewer.log_contacts(self.contacts, self.state_0)


###
# Kernels
###


@wp.kernel
def _step_time(
    # Inputs:
    dt: wp.float32,
    # Outputs:
    time: wp.array[wp.float32],
):
    time[0] = time[0] + dt


@wp.kernel
def _apply_external_force_to_box(
    # Inputs:
    gravity: wp.array[wp.vec3],
    body_mass: wp.array[wp.float32],
    time: wp.array[wp.float32],
    contact_count: wp.array[wp.int32],
    contact_shape0: wp.array[wp.int32],
    contact_shape1: wp.array[wp.int32],
    shape_material_mu: wp.array[wp.float32],
    # Outputs:
    state_body_f: wp.array[wp.spatial_vectorf],
):
    """
    A kernel to apply a time-dependent external force to the box.

    The force will be zero until t = FORCE_START_TIME,
    then ramp up linearly until t = FORCE_END_TIME, with a final value
    of MAX_FORCE times the minimal force required to make the box slip.
    The force is then zero again after t = FORCE_END_TIME.
    """
    # Retrieve the body index from the thread index
    bid = wp.tid()

    # Retrieve number of active contacts in the world
    nc = contact_count[0]

    # Retrieve the mass of the box
    m = body_mass[bid]

    # Retrieve the gravitational acceleration
    g = wp.norm_l2(gravity[0])

    # Define the time window for the active external force profile
    t_start = wp.float32(FORCE_START_TIME)
    t_end = wp.float32(FORCE_END_TIME)

    # Get the current time
    t = time[0]

    # Apply a time-dependent external force
    if t > t_start and t < t_end and nc > 0:
        s0 = contact_shape0[0]
        s1 = contact_shape1[0]
        mu0 = shape_material_mu[s0]
        mu1 = shape_material_mu[s1]
        mu = 0.5 * (mu0 + mu1)  # Get friction coefficient (of first contact)
        f_max = wp.float32(MAX_FORCE) * m * g * mu
        f_ext = (t - t_start) / (t_end - t_start) * f_max
        state_body_f[bid] = wp.spatial_vectorf(f_ext, 0.0, 0.0, 0.0, -0.1 * f_ext, 0.0)
    else:
        state_body_f[bid] = wp.spatial_vectorf(0.0, 0.0, 0.0, 0.0, 0.0, 0.0)


###
# Launchers
###


def apply_external_force_to_box(setup: SolverSetup):
    """
    Applies a time-dependent external force to the box.
    """
    wp.launch(
        kernel=_apply_external_force_to_box,
        dim=setup.model.body_count,
        inputs=[
            setup.model.gravity,
            setup.model.body_mass,
            setup.time,
            setup.contacts.rigid_contact_count,
            setup.contacts.rigid_contact_shape0,
            setup.contacts.rigid_contact_shape1,
            setup.model.shape_material_mu,
        ],
        outputs=[setup.state_0.body_f],
        device=setup.model.device,
    )


###
# Helpers
###


def make_setup_solver_kamino(asset_file: str, dt: float, max_frames: int) -> SolverSetup:
    robot_builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverKamino.register_custom_attributes(robot_builder)
    robot_builder.default_shape_cfg.margin = 0.0
    robot_builder.default_shape_cfg.gap = 0.0
    robot_builder.add_usd(
        asset_file,
        force_position_velocity_actuation=True,
        collapse_fixed_joints=True,
        enable_self_collisions=True,
        hide_collision_shapes=True,
    )
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    builder.request_state_attributes("body_parent_f")
    builder.request_contact_attributes("force")
    builder.add_world(robot_builder)
    builder.add_ground_plane()
    model = builder.finalize(skip_validation_joints=True)
    solver_config = newton.solvers.SolverKamino.Config.from_model(model)
    solver_config.padmm.primal_tolerance = 1e-4
    solver_config.padmm.dual_tolerance = 1e-4
    solver_config.padmm.compl_tolerance = 1e-4
    solver_config.padmm.max_iterations = 200
    solver_config.padmm.rho_0 = 0.1
    solver_config.padmm.warmstart_mode = "none"
    solver = newton.solvers.SolverKamino(model=model, config=solver_config)
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="kamino",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    solver.reset(state_out=setup.state_0)
    return setup


def make_setup_solver_mujoco(asset_file: str, dt: float, max_frames: int) -> SolverSetup:
    articulation_builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverMuJoCo.register_custom_attributes(articulation_builder)
    articulation_builder.default_joint_cfg = newton.ModelBuilder.JointDofConfig(
        limit_ke=1.0e3, limit_kd=1.0e1, friction=1e-5
    )
    articulation_builder.default_shape_cfg.ke = 6.0e3
    articulation_builder.default_shape_cfg.kd = 1.6e2
    articulation_builder.default_shape_cfg.kf = 1.0e3
    articulation_builder.default_shape_cfg.mu = 0.75
    articulation_builder.default_shape_cfg.mu_rolling = 0.0
    articulation_builder.default_shape_cfg.mu_torsional = 0.0
    articulation_builder.add_usd(
        asset_file,
        collapse_fixed_joints=False,
        enable_self_collisions=False,
        hide_collision_shapes=True,
    )
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    builder.request_state_attributes("body_parent_f")
    builder.request_contact_attributes("force")
    builder.add_world(articulation_builder)
    builder.default_shape_cfg.ke = 6.0e3
    builder.default_shape_cfg.kd = 1.6e2
    builder.default_shape_cfg.mu_rolling = 0.0
    builder.default_shape_cfg.mu_torsional = 0.0
    builder.add_ground_plane()
    model = builder.finalize()
    solver = newton.solvers.SolverMuJoCo(
        model,
        cone="elliptic",
        impratio=100,
        iterations=200,
        ls_iterations=100,
        nconmax=46,
        njmax=100,
        use_mujoco_contacts=False,
    )
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="mujoco",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    return setup


def make_setup_solver_xpbd(asset_file: str, dt: float, max_frames: int) -> SolverSetup:
    articulation_builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverXPBD.register_custom_attributes(articulation_builder)
    articulation_builder.default_joint_cfg = newton.ModelBuilder.JointDofConfig(
        limit_ke=1.0e3, limit_kd=1.0e1, friction=1e-5
    )
    articulation_builder.default_shape_cfg.ke = 2.0e3
    articulation_builder.default_shape_cfg.kd = 1.0e2
    articulation_builder.default_shape_cfg.kf = 1.0e3
    articulation_builder.default_shape_cfg.mu = 0.75
    articulation_builder.add_usd(
        asset_file,
        collapse_fixed_joints=False,
        enable_self_collisions=False,
        hide_collision_shapes=True,
    )
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    builder.request_state_attributes("body_parent_f")
    builder.request_contact_attributes("force")
    builder.add_world(articulation_builder)
    builder.default_shape_cfg.ke = 1.0e3
    builder.default_shape_cfg.kd = 1.0e2
    builder.add_ground_plane()
    model = builder.finalize()
    solver = newton.solvers.SolverXPBD(
        model,
        iterations=20,
        soft_body_relaxation=0.9,
        soft_contact_relaxation=0.9,
        joint_linear_relaxation=0.7,
        joint_angular_relaxation=0.4,
        joint_linear_compliance=0.0,
        joint_angular_compliance=0.0,
        rigid_contact_relaxation=0.8,
        rigid_contact_con_weighting=True,
        angular_damping=0.0,
        enable_restitution=False,
    )
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="xpbd",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    return setup


###
# Runtime
###


class Example:
    def __init__(self, viewer: newton.viewer.ViewerBase, args, use_graph=True, start_paused=False):
        # Set simulation run-time configurations
        self.viewer_fps = 50
        self.viewer_dt = 1.0 / self.viewer_fps
        target_sim_dt = 0.0025  # 400 fps
        self.sim_substeps = max(1, round(self.viewer_dt / target_sim_dt))
        self.sim_dt = self.viewer_dt / self.sim_substeps
        msg.notif(f"Using sim_dt = {self.sim_dt} ({self.sim_substeps} substeps per frame)")
        self.sim_time = 0.0
        self.viewer = viewer
        self.device = wp.get_device()
        self.use_graph = use_graph
        self.start_paused = start_paused

        # External forces: applied in viewer vs automatically (force ramp up)
        self.viewer_forces = False

        # Define the asset file
        assets_dir = os.path.join(get_kamino_assets_directory(), "validation")
        asset_file = os.path.join(assets_dir, "puck_on_plane_articulated.usda")

        # Create the solver setups
        self.setup_kamino = make_setup_solver_kamino(asset_file, self.sim_dt, 5000)
        self.setup_mujoco = make_setup_solver_mujoco(asset_file, self.sim_dt, 5000)
        self.setup_xpbd = make_setup_solver_xpbd(asset_file, self.sim_dt, 5000)

        # Solver setup choice
        self.setup_names = ["Kamino", "MuJoCo", "XPBD"]
        self.setups = [self.setup_kamino, self.setup_mujoco, self.setup_xpbd]
        self.current_setup_id = 0
        self.init_setup(reset_viewer=True, first=True)

    @property
    def setup(self):
        return self.setups[self.current_setup_id]

    def capture(self):
        self.graph = None
        if self.device.is_cuda:
            with wp.ScopedCapture() as capture:
                self.simulate()
            self.graph = capture.graph

    def reset(self):
        self.setup.reset()

    def init_setup(self, reset_viewer=True, first=False):
        msg.notif(f"Initializing {self.setup_names[self.current_setup_id]} solver")
        # Reset state
        self.reset()

        # Set model in viewer
        if reset_viewer:
            self.viewer.set_model(self.setup.model)
            self.viewer._paused = self.start_paused  # Start paused to inspect the initial configuration
            if hasattr(self.viewer, "set_camera"):  # Set initial camera on viewer
                camera_pos = wp.vec3(0.5, -2.0, 0.6)
                pitch = -15.0
                yaw = 90.0
                self.viewer.set_camera(camera_pos, pitch, yaw)
            self.viewer.contact_viz_scale = 2.0 * self.viewer._contact_viz_scale_default
            self.viewer.show_contacts = True
            self.viewer.vsync = True
        if reset_viewer and not first and hasattr(self.viewer, "register_ui_callback"):
            # We skip GUI registration on first call as it is done in newton.examples.run() automatically
            self.viewer.register_ui_callback(lambda ui, ex=self: ex.gui(ui), position="side")

        # Reset graph
        self.graph = None

        # Warm-up simulation
        self.setup.step(self.setup.state_0, self.sim_dt)
        self.reset()

        # Capture graph again
        if self.use_graph:
            self.capture()

    # simulate() performs one frame's worth of updates
    def simulate(self):
        for _ in range(self.sim_substeps):
            # Clear and apply forces to the solver state
            self.setup.state_0.clear_forces()
            if self.viewer_forces:
                self.viewer.apply_forces(self.setup.state_0)
            else:
                apply_external_force_to_box(self.setup)

            # Step solver
            self.setup.step(self.setup.state_0, self.sim_dt)

            # Swap the leading solver state
            self.setup.state_0, self.setup.state_1 = self.setup.state_1, self.setup.state_0

    def step(self):
        if self.graph:
            wp.capture_launch(self.graph)
        else:
            self.simulate()
        self.sim_time += self.viewer_dt

    def render(self):
        self.viewer.begin_frame(self.sim_time)
        self.setup.render(self.viewer)
        self.viewer.end_frame()

    @staticmethod
    def create_parser():
        return newton.examples.create_parser()

    def gui(self, imgui):
        # Checkbox to toggle force input (applied in viewer, or automatic force ramp-up)
        clicked, self.viewer_forces = imgui.checkbox("User-applied forces", self.viewer_forces)
        if clicked:
            self.init_setup(reset_viewer=False)

        # Toggle for solver backend
        imgui.text("Solver backend")
        if imgui.begin_combo("##solver_combo", self.setup_names[self.current_setup_id]):
            for solver_id, solver_name in enumerate(self.setup_names):
                selected = solver_id == self.current_setup_id
                clicked, _ = imgui.selectable(solver_name, selected)
                if clicked:
                    self.current_setup_id = solver_id
                    self.init_setup(reset_viewer=True)
                if selected:
                    imgui.set_item_default_focus()
            imgui.end_combo()

        # Reset button (using the solver-internal reset, rather than fully reloading the example and GUI)
        if imgui.button("Reset##custom_reset"):
            self.reset()


if __name__ == "__main__":
    parser = Example.create_parser()
    viewer, args = newton.examples.init(parser)
    example = Example(viewer, args, use_graph=True, start_paused=False)

    newton.examples.run(example, args)
