# SPDX-FileCopyrightText: Copyright (c) 2025 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

###########################################################################
# Box on Plane Example - Multi-Solver Comparison
###########################################################################

import dataclasses
import os

import numpy as np
import warp as wp

import newton
import newton.examples

# from newton._src.solvers.kamino._src.metrics import SolutionMetricsNewton, SolutionMetricsLogger
from newton._src.solvers.kamino._src.utils import logger as msg
from newton._src.solvers.kamino.examples import get_examples_output_path
from newton._src.solvers.kamino.examples.validation.viewer_recording import enable_recording
from newton.tests import get_kamino_assets_directory

np.set_printoptions(linewidth=20000, precision=6, threshold=10000, suppress=True)

START_HEIGHT = 1.0
FRICTION = 0.7
RESTITUTION = 0.8
RECORD_END_TIME = 7.0


def eval_kd(ke, epsilon):
    # Approximate restitution coefficient epsilon created by damping ratio zeta
    # is epsilon = exp(- pi * zeta / sqrt(1 - zeta^2))
    # We invert this formula (keeping the positive root) to compute the damping ratio given epsilon
    temp = -np.log(epsilon)
    temp2 = temp * temp
    zeta = np.sqrt(temp2 / (temp2 + np.pi * np.pi))

    # Set kd given ke and the damping ratio zeta = kd / (2 * sqrt(ke))
    return zeta * 2.0 * np.sqrt(ke)


MUJOCO_KE = 6.0e3
MUJOCO_KD = eval_kd(MUJOCO_KE, RESTITUTION)  # Set K_d to emulate target restitution (by under-damping)
MUJOCO_IMPRATIO = 100.0


###
# Classes
###


@dataclasses.dataclass
class SolverSetup:
    # Required inputs
    name: str
    builder: newton.ModelBuilder
    model: newton.Model
    solver: newton.solvers.SolverBase

    # Generated by the model
    state_0: newton.State | None = None
    state_1: newton.State | None = None
    control: newton.Control | None = None
    contacts: newton.Contacts | None = None

    # Time
    time: wp.array | None = None

    # metrics: SolutionMetricsNewton | None = None
    # logger: SolutionMetricsLogger | None = None

    def __post_init__(self):
        self._ref_state = self.model.state()  # Origin state to reset to
        self.state_0 = self.model.state()
        self.state_1 = self.model.state()

        # For Kamino: "reset" the states to populate Kamino-specific arrays (to not break state.assign())
        if hasattr(self.solver, "reset"):
            self.solver.reset(self._ref_state)
            self.solver.reset(self.state_0)
            self.solver.reset(self.state_1)
        self.state_0.assign(self._ref_state)
        self.state_1.assign(self._ref_state)
        print(f"Initial bodies: {self._ref_state.body_q.numpy()}")

        self.control = self.model.control()
        self.contacts = self.model.contacts()
        self.time = wp.zeros(dtype=wp.float32, shape=1, device=self.model.device)

    def step(self, state_in: newton.State, sim_dt: float):
        self.model.collide(state_in, self.contacts)
        self.solver.step(state_in, self.state_1, self.control, self.contacts, sim_dt)
        # Pull per-contact forces back into self.contacts.force (when allocated) so
        # the viewer's "Show Contacts -> Forces" / "Modes" layers have data to draw.
        self.solver.update_contacts(self.contacts, self.state_1)
        # self.metrics.evaluate(self.state_1, self.state_0, self.control, self.contacts)
        # self.logger.log()
        wp.launch(_step_time, dim=1, inputs=[sim_dt, self.time])

    def reset(self):
        self.state_0.assign(self._ref_state)
        self.state_1.assign(self._ref_state)
        self.control.clear()
        self.contacts.clear()
        self.time.zero_()
        if hasattr(self.solver, "reset"):
            self.solver.reset(self.state_0)

    def render(self, viewer: newton.viewer.ViewerBase):
        viewer.log_state(self.state_0)
        viewer.log_contacts(self.contacts, self.state_0)


###
# Kernels
###


@wp.kernel
def _step_time(
    # Inputs:
    dt: wp.float32,
    # Outputs:
    time: wp.array[wp.float32],
):
    time[0] = time[0] + dt


###
# Helpers
###


def build_sphere_on_plane(
    builder: newton.ModelBuilder | None = None,
    radius: float = 0.1,
    mass: float = 1.0,
    z_offset: float = 0.0,
    friction: float | None = None,
    restitution: float | None = None,
    ground: bool = True,
    new_world: bool = True,
    use_custom_shape_cfg: bool = False,
    use_box: bool = False,
) -> newton.ModelBuilder:
    """
    Constructs a basic model of a free-floating 'box' body and a ground box geom.

    Args:
        builder (ModelBuilder | None):
            An optional existing model builder to populate.\n
            If `None`, a new builder is created.
        z_offset (float):
            A vertical offset to apply to the initial position of the box.
        ground (bool):
            Whether to add a static ground plane to the model.
        new_world (bool):
            Whether to begin a new world in the builder for this model.\n
            If `True` (or `builder` is `None`), the model is wrapped in a new world context
            opened via :meth:`ModelBuilder.begin_world` and closed via
            :meth:`ModelBuilder.end_world`.\n
            If `False`, the caller must already be inside an active world; the model is then
            added to that currently active world.

    Returns:
        ModelBuilder: The populated model builder.
    """
    from newton._src.geometry import inertia  # noqa: PLC0415

    # Create a new builder if none is provided
    if builder is None:
        _builder = newton.ModelBuilder()
    else:
        _builder = builder

    # Begin a new world in the builder if requested or if a new builder was created
    if new_world or builder is None:
        _builder.begin_world(label="bouncing_ball")

    # Add the sphere/box body
    r_i: float = radius
    m_i: float = mass
    if not use_box:
        i_I_i = inertia.compute_inertia_sphere_from_mass(mass=m_i, radius=r_i)
    else:
        i_I_i = inertia.compute_inertia_box_from_mass(mass=m_i, hx=r_i, hy=r_i, hz=r_i)
    xform = wp.transformf(0.0, 0.0, r_i + z_offset, 0.0, 0.0, 0.0, 1.0)
    bid0 = _builder.add_body(
        label="sphere" if not use_box else "box",
        mass=m_i,
        inertia=i_I_i,
        xform=xform,
        lock_inertia=True,
    )

    # Use custom shape config if requested
    custom_shape_cfg = (
        newton.ModelBuilder.ShapeConfig(
            gap=0.0,
            margin=0.0,
            mu=friction if friction is not None else _builder.default_shape_cfg.mu,
            restitution=restitution if restitution is not None else _builder.default_shape_cfg.restitution,
        )
        if use_custom_shape_cfg
        else _builder.default_shape_cfg
    )

    # Add collision geometries
    if not use_box:
        _builder.add_shape_sphere(
            label="sphere_geom",
            body=bid0,
            radius=r_i,
            cfg=custom_shape_cfg,
        )
    else:
        _builder.add_shape_box(
            label="sphere_geom",
            body=bid0,
            hx=r_i,
            hy=r_i,
            hz=r_i,
            cfg=custom_shape_cfg,
        )

    # Add a static collision geometry for the plane
    if ground:
        _builder.add_ground_plane(
            cfg=custom_shape_cfg,
            label="ground",
            height=0.0,
        )

    # Close the world context if we opened one
    if new_world or builder is None:
        _builder.end_world()

    # Return the populated model builder
    return _builder


def make_setup_solver_kamino(dt: float, max_frames: int, use_box: bool = False) -> SolverSetup:
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverKamino.register_custom_attributes(builder)
    builder.request_contact_attributes("force")
    build_sphere_on_plane(
        builder=builder,
        radius=0.1,
        mass=1.0,
        z_offset=START_HEIGHT,
        friction=FRICTION,
        restitution=RESTITUTION,
        ground=True,
        use_custom_shape_cfg=True,
        use_box=use_box,
    )
    model = builder.finalize(skip_validation_joints=True)
    model.rigid_contact_max = 4
    solver_config = newton.solvers.SolverKamino.Config.from_model(model)
    solver_config.padmm.primal_tolerance = 1e-6
    solver_config.padmm.dual_tolerance = 1e-6
    solver_config.padmm.compl_tolerance = 1e-6
    solver_config.padmm.max_iterations = 200
    solver_config.padmm.rho_0 = 1.0
    solver_config.padmm.warmstart_mode = "none"
    solver = newton.solvers.SolverKamino(model=model, config=solver_config)
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="kamino",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    solver.reset(state_out=setup.state_0)
    return setup


def make_setup_solver_mujoco(dt: float, max_frames: int, use_box: bool = False) -> SolverSetup:
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverMuJoCo.register_custom_attributes(builder)
    builder.default_joint_cfg = newton.ModelBuilder.JointDofConfig(limit_ke=1.0e3, limit_kd=1.0e1, friction=1e-5)
    builder.default_shape_cfg.margin = 0.0
    builder.default_shape_cfg.gap = 0.0
    builder.default_shape_cfg.ke = MUJOCO_KE
    builder.default_shape_cfg.kd = MUJOCO_KD
    builder.default_shape_cfg.mu = 0.75
    builder.default_shape_cfg.mu_rolling = 0.0
    builder.default_shape_cfg.mu_torsional = 0.0
    builder.request_contact_attributes("force")
    build_sphere_on_plane(
        builder=builder,
        radius=0.1,
        mass=1.0,
        z_offset=START_HEIGHT,
        friction=FRICTION,
        restitution=RESTITUTION,
        ground=True,
        use_custom_shape_cfg=False,  # Emulated restitution for MuJoCo will come from the default config above
        use_box=use_box,
    )
    model = builder.finalize()
    solver = newton.solvers.SolverMuJoCo(
        model,
        cone="elliptic",
        impratio=MUJOCO_IMPRATIO,
        iterations=200,
        ls_iterations=100,
        nconmax=46,
        njmax=100,
        use_mujoco_contacts=False,
    )
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="mujoco",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    return setup


def make_setup_solver_xpbd(dt: float, max_frames: int, use_box: bool = False) -> SolverSetup:
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverXPBD.register_custom_attributes(builder)
    builder.default_joint_cfg = newton.ModelBuilder.JointDofConfig(limit_ke=1.0e3, limit_kd=1.0e1, friction=1e-5)
    builder.default_shape_cfg.margin = 0.0
    builder.default_shape_cfg.gap = 0.0
    builder.default_shape_cfg.ke = 2.0e3
    builder.default_shape_cfg.kd = 1.0e2
    builder.default_shape_cfg.kf = 1.0e3
    builder.default_shape_cfg.mu = 0.75
    builder.request_contact_attributes("force")
    build_sphere_on_plane(
        builder=builder,
        radius=0.1,
        mass=1.0,
        z_offset=START_HEIGHT,
        friction=FRICTION,
        restitution=RESTITUTION,
        ground=True,
        use_custom_shape_cfg=True,
        use_box=use_box,
    )
    model = builder.finalize()
    model.rigid_contact_max = 4
    solver = newton.solvers.SolverXPBD(
        model,
        iterations=20,
        soft_body_relaxation=0.9,
        soft_contact_relaxation=0.9,
        joint_linear_relaxation=0.7,
        joint_angular_relaxation=0.4,
        joint_linear_compliance=0.0,
        joint_angular_compliance=0.0,
        rigid_contact_relaxation=0.8,
        rigid_contact_con_weighting=True,
        angular_damping=0.0,
        enable_restitution=True,
    )
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="xpbd",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    return setup


###
# Runtime
###


class Example:
    def __init__(self, viewer: newton.viewer.ViewerBase, args, use_graph=True, start_paused=False):
        # Set simulation run-time configurations
        self.viewer_fps = 50
        self.viewer_dt = 1.0 / self.viewer_fps
        target_sim_dt = 0.0025  # 400 fps
        self.sim_substeps = max(1, round(self.viewer_dt / target_sim_dt))
        self.sim_dt = self.viewer_dt / self.sim_substeps
        msg.notif(f"Using sim_dt = {self.sim_dt} ({self.sim_substeps} substeps per frame)")
        self.sim_time = 0.0
        self.viewer = viewer
        self.args = args
        self.device = wp.get_device()
        self.use_graph = use_graph
        self.start_paused = start_paused

        # Whether to switch the geometry to a box
        use_box = False

        # Setup trajectory recording
        self.record_traj = False
        self.frame_id = 0
        if self.record_traj:
            self.num_recording_frames = int(np.floor(RECORD_END_TIME / self.viewer_dt)) + 1
            self.traj = np.zeros((self.num_recording_frames, 3))
            self.recording_folder = os.path.join(
                get_examples_output_path(), "bouncing_ball" if not use_box else "bouncing_box"
            )
            os.makedirs(self.recording_folder, exist_ok=True)

        # Clip recording state
        self.record_clips = False
        if getattr(args, "record", None):
            self.video_target_frames = int(np.floor(RECORD_END_TIME / self.viewer_dt)) + 1

        # External forces: applied in viewer vs automatically (currently none)
        self.viewer_forces = True

        # Create the solver setups
        self.setup_kamino = make_setup_solver_kamino(self.sim_dt, 5000, use_box=use_box)
        self.setup_mujoco = make_setup_solver_mujoco(self.sim_dt, 5000, use_box=use_box)
        self.setup_xpbd = make_setup_solver_xpbd(self.sim_dt, 5000, use_box=use_box)

        # Load reference trajectory
        self.use_ref_traj = False
        ref_folder = os.path.join(get_kamino_assets_directory(), "validation", "Reference")
        self.body_q_ref = np.load(os.path.join(ref_folder, "body_q_ref_bouncing_ball.npy"))

        # Solver setup choice
        self.setup_names = ["Kamino", "MuJoCo", "XPBD", "Reference"]
        self.setups = [self.setup_kamino, self.setup_mujoco, self.setup_xpbd, self.setup_kamino]
        self.current_setup_id = 0
        self.init_setup(reset_viewer=True, first=True)

    @property
    def setup(self):
        return self.setups[self.current_setup_id]

    def capture(self):
        self.graph = None
        if self.device.is_cuda:
            with wp.ScopedCapture() as capture:
                self.simulate()
            self.graph = capture.graph

    def reset(self):
        self.frame_id = 0
        self.setup.reset()

    def start_recording_clip(self):
        """Start a new video clip for the currently active solver."""
        if not hasattr(self.viewer, "start_clip"):
            msg.warning("Recording is not enabled (pass --record sync|async at launch).")
            return
        solver_name = self.setup_names[self.current_setup_id]
        self.viewer.start_clip(
            output_path=os.path.join(self.args.video_base_dir, f"recording_{solver_name}.mp4"),
            max_frames=self.video_target_frames,
            video_folder=os.path.join(self.args.video_base_dir, f"frames_{solver_name}"),
            fps=self.viewer_fps,
            keep_frames=self.args.keep_frames,
        )

    def init_setup(self, reset_viewer=True, first=False):
        solver_name = self.setup_names[self.current_setup_id]
        self.use_ref_traj = solver_name == "Reference"
        msg.notif(f"Initializing {solver_name} solver")

        # Reset state
        self.reset()

        # Set model in viewer
        if reset_viewer:
            self.viewer.set_model(self.setup.model)
            self.viewer._paused = self.start_paused  # Start paused to inspect the initial configuration
            if hasattr(self.viewer, "set_camera"):  # Set initial camera on viewer
                camera_pos = wp.vec3(4.0, 0.0, 1.0)
                pitch = -5.0
                yaw = 180.0
                self.viewer.set_camera(camera_pos, pitch, yaw)
            self.viewer.show_contacts = True
            self.viewer.vsync = True
        if reset_viewer and not first and hasattr(self.viewer, "register_ui_callback"):
            # We skip GUI registration on first call as it is done in newton.examples.run() automatically
            self.viewer.register_ui_callback(lambda ui, ex=self: ex.gui(ui), position="side")

        # Reset graph
        self.graph = None

        # Warm-up simulation
        self.setup.step(self.setup.state_0, self.sim_dt)
        self.reset()

        # Capture graph again
        if self.use_graph:
            self.capture()

    # simulate() performs one frame's worth of updates
    def simulate(self):
        for _ in range(self.sim_substeps):
            # Clear and apply forces to the solver state
            self.setup.state_0.clear_forces()
            if self.viewer_forces:
                self.viewer.apply_forces(self.setup.state_0)

            # Step solver
            self.setup.step(self.setup.state_0, self.sim_dt)

            # Swap the leading solver state
            self.setup.state_0, self.setup.state_1 = self.setup.state_1, self.setup.state_0

    def step(self):
        # Optionally record trajectory (before step so we capture the first frame)
        if self.record_traj:
            if self.frame_id < self.num_recording_frames:
                self.traj[self.frame_id] = self.setup.state_0.body_q.numpy()[0, :3]
                if self.frame_id == self.num_recording_frames - 1:
                    solver_name = self.setup_names[self.current_setup_id]
                    np.save(os.path.join(self.recording_folder, f"traj_{solver_name}_{RESTITUTION}.npy"), self.traj)
                    msg.notif("Trajectory recorded")

        # Perform step
        if self.graph:
            wp.capture_launch(self.graph)
        else:
            self.simulate()
        self.sim_time += self.viewer_dt
        self.frame_id += 1

        # Optionally overwrite state with reference solution
        if self.use_ref_traj:
            if self.frame_id < self.body_q_ref.shape[0]:
                self.setup.state_0.body_q.assign(self.body_q_ref[self.frame_id])

    def render(self):
        self.viewer.begin_frame(self.sim_time)
        self.setup.render(self.viewer)
        self.viewer.end_frame()

    @staticmethod
    def create_parser():
        return newton.examples.create_parser()

    def gui(self, imgui):
        # Checkbox to toggle force input (applied in viewer, or automatic force ramp-up)
        clicked, self.viewer_forces = imgui.checkbox("User-applied forces", self.viewer_forces)
        if clicked:
            self.init_setup(reset_viewer=False)

        # Toggle for solver backend
        imgui.text("Solver backend")
        if imgui.begin_combo("##solver_combo", self.setup_names[self.current_setup_id]):
            for solver_id, solver_name in enumerate(self.setup_names):
                selected = solver_id == self.current_setup_id
                clicked, _ = imgui.selectable(solver_name, selected)
                if clicked:
                    self.current_setup_id = solver_id
                    self.init_setup(reset_viewer=True)
                if selected:
                    imgui.set_item_default_focus()
            imgui.end_combo()

        # Checkbox to record a clip on the next Reset press
        if getattr(self.args, "record", None) and hasattr(self.viewer, "start_clip"):
            _, self.record_clips = imgui.checkbox("Record clip on Reset", self.record_clips)

        # Reset button (using the solver-internal reset, rather than fully reloading the example and GUI)
        if imgui.button("Reset##custom_reset"):
            self.reset()
            if self.record_clips and hasattr(self.viewer, "start_clip"):
                self.start_recording_clip()


if __name__ == "__main__":
    parser = Example.create_parser()
    parser.add_argument(
        "--record",
        type=str,
        choices=["sync", "async"],
        default="async",
        help="Enable frame recording: 'sync' for synchronous, 'async' for non-blocking",
    )
    parser.add_argument(
        "--video-output",
        type=str,
        default=None,
        help="Output MP4 path (defaults to <examples_output>/bouncing_ball/recording.mp4)",
    )
    parser.add_argument(
        "--keep-frames",
        type=bool,
        default=True,
        help="Keep recorded PNG frames after the MP4 has been generated",
    )
    viewer, args = newton.examples.init(parser)

    recording_dir = os.path.join(get_examples_output_path(), "bouncing_ball")
    args.video_base_dir = recording_dir
    if args.record:
        viewer = enable_recording(
            viewer,
            record_video=True,
            video_folder=os.path.join(recording_dir, "frames"),
            async_save=(args.record == "async"),
        )

    example = Example(viewer, args, use_graph=True, start_paused=False)

    newton.examples.run(example, args)
