# SPDX-FileCopyrightText: Copyright (c) 2025 The Newton Developers
# SPDX-License-Identifier: Apache-2.0

###########################################################################
# Box on Plane Example - Multi-Solver Comparison
###########################################################################

import dataclasses
import os

import numpy as np
import warp as wp

import newton
import newton.examples

# from newton._src.solvers.kamino._src.metrics import SolutionMetricsNewton, SolutionMetricsLogger
from newton._src.solvers.kamino._src.utils import logger as msg
from newton._src.solvers.kamino.examples import get_examples_output_path
from newton._src.solvers.kamino.examples.validation.viewer_recording import enable_recording
from newton.tests import get_kamino_assets_directory

np.set_printoptions(linewidth=20000, precision=6, threshold=10000, suppress=True)

FORCE_START_TIME = 1.0
FORCE_END_TIME = 5.0
MAX_FORCE = 1.5
RECORD_END_TIME = 7.0

MUJOCO_KE = 6.0e3
MUJOCO_KD = 2.0 * np.sqrt(MUJOCO_KE)  # Set K_d for critical damping
MUJOCO_IMPRATIO = 100.0


###
# Classes
###


@dataclasses.dataclass
class SolverSetup:
    # Required inputs
    name: str
    builder: newton.ModelBuilder
    model: newton.Model
    solver: newton.solvers.SolverBase

    # Generated by the model
    state_0: newton.State | None = None
    state_1: newton.State | None = None
    control: newton.Control | None = None
    contacts: newton.Contacts | None = None

    # Time
    time: wp.array | None = None

    # metrics: SolutionMetricsNewton | None = None
    # logger: SolutionMetricsLogger | None = None

    def __post_init__(self):
        self._ref_state = self.model.state()  # Origin state to reset to
        self.state_0 = self.model.state()
        self.state_1 = self.model.state()

        # For Kamino: "reset" the states to populate Kamino-specific arrays (to not break state.assign())
        if hasattr(self.solver, "reset"):
            self.solver.reset(self._ref_state)
            self.solver.reset(self.state_0)
            self.solver.reset(self.state_1)
        self.state_0.assign(self._ref_state)
        self.state_1.assign(self._ref_state)

        self.control = self.model.control()
        self.contacts = self.model.contacts()
        self.time = wp.zeros(dtype=wp.float32, shape=1, device=self.model.device)

    def step(self, state_in: newton.State, sim_dt: float):
        self.model.collide(state_in, self.contacts)
        self.solver.step(state_in, self.state_1, self.control, self.contacts, sim_dt)
        # Pull per-contact forces back into self.contacts.force (when allocated) so
        # the viewer's "Show Contacts -> Forces" / "Modes" layers have data to draw.
        self.solver.update_contacts(self.contacts, self.state_1)
        # self.metrics.evaluate(self.state_1, self.state_0, self.control, self.contacts)
        # self.logger.log()
        wp.launch(_step_time, dim=1, inputs=[sim_dt, self.time])

    def reset(self):
        self.state_0.assign(self._ref_state)
        self.state_1.assign(self._ref_state)
        self.control.clear()
        self.contacts.clear()
        self.time.zero_()
        if hasattr(self.solver, "reset"):
            self.solver.reset(self.state_0)

    def render(self, viewer: newton.viewer.ViewerBase):
        viewer.log_state(self.state_0)
        viewer.log_contacts(self.contacts, self.state_0)


###
# Kernels
###


@wp.kernel
def _step_time(
    # Inputs:
    dt: wp.float32,
    # Outputs:
    time: wp.array[wp.float32],
):
    time[0] = time[0] + dt


###
# Helpers
###


def make_setup_solver_kamino(asset_file: str, dt: float, max_frames: int, alpha: float) -> SolverSetup:
    robot_builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverKamino.register_custom_attributes(robot_builder)
    robot_builder.default_shape_cfg.margin = 0.0
    robot_builder.default_shape_cfg.gap = 0.0
    robot_builder.add_usd(
        asset_file,
        force_position_velocity_actuation=True,
        collapse_fixed_joints=False,
        enable_self_collisions=True,
        hide_collision_shapes=True,
    )
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    builder.request_state_attributes("body_parent_f")
    builder.request_contact_attributes("force")
    builder.add_world(robot_builder)
    builder.add_ground_plane(cfg=newton.ModelBuilder.ShapeConfig(collision_group=-1))
    model = builder.finalize(skip_validation_joints=True)
    solver_config = newton.solvers.SolverKamino.Config.from_model(model)
    solver_config.padmm.primal_tolerance = 1e-4
    solver_config.padmm.dual_tolerance = 1e-4
    solver_config.padmm.compl_tolerance = 1e-4
    solver_config.padmm.max_iterations = 200
    solver_config.padmm.rho_0 = 0.1
    solver_config.padmm.warmstart_mode = "none"
    solver_config.constraints.alpha = alpha
    solver = newton.solvers.SolverKamino(model=model, config=solver_config)
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="kamino",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    solver.reset(state_out=setup.state_0)
    return setup


def make_setup_solver_mujoco(asset_file: str, dt: float, max_frames: int, T: float) -> SolverSetup:
    articulation_builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverMuJoCo.register_custom_attributes(articulation_builder)
    articulation_builder.default_joint_cfg = newton.ModelBuilder.JointDofConfig(
        limit_ke=1.0e3, limit_kd=1.0e1, friction=0.0
    )
    articulation_builder.default_shape_cfg.margin = 0.0
    articulation_builder.default_shape_cfg.gap = 0.0
    articulation_builder.default_shape_cfg.ke = MUJOCO_KE
    articulation_builder.default_shape_cfg.kd = MUJOCO_KD
    articulation_builder.default_shape_cfg.mu = 0.75
    articulation_builder.default_shape_cfg.mu_rolling = 0.0
    articulation_builder.default_shape_cfg.mu_torsional = 0.0
    articulation_builder.add_usd(
        asset_file,
        collapse_fixed_joints=False,
        enable_self_collisions=False,
        hide_collision_shapes=True,
    )
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    builder.request_state_attributes("body_parent_f")
    builder.request_contact_attributes("force")
    builder.add_world(articulation_builder)
    builder.default_shape_cfg.margin = 0.0
    builder.default_shape_cfg.gap = 0.0
    builder.default_shape_cfg.ke = MUJOCO_KE
    builder.default_shape_cfg.kd = MUJOCO_KD
    builder.default_shape_cfg.mu_rolling = 0.0
    builder.default_shape_cfg.mu_torsional = 0.0
    builder.add_ground_plane(cfg=newton.ModelBuilder.ShapeConfig(collision_group=-1))
    model = builder.finalize()
    solver = newton.solvers.SolverMuJoCo(
        model,
        cone="elliptic",
        impratio=MUJOCO_IMPRATIO,
        iterations=200,
        ls_iterations=100,
        nconmax=46,
        njmax=100,
        use_mujoco_contacts=False,
    )

    # Set equality constraint stiffness
    eq_solref_np = np.array([[T, 1.0]])
    eq_solimp_np = np.array([[0.99, 0.999, 0.001, 0.5, 2.0]])
    solver.mjw_model.eq_solref.assign(eq_solref_np)
    solver.mjw_model.eq_solimp.assign(eq_solimp_np)

    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="mujoco",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    return setup


def make_setup_solver_xpbd(asset_file: str, dt: float, max_frames: int) -> SolverSetup:
    articulation_builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    newton.solvers.SolverXPBD.register_custom_attributes(articulation_builder)
    articulation_builder.default_joint_cfg = newton.ModelBuilder.JointDofConfig(
        limit_ke=1.0e3, limit_kd=1.0e1, friction=0.0
    )
    articulation_builder.default_shape_cfg.margin = 0.0
    articulation_builder.default_shape_cfg.gap = 0.0
    articulation_builder.default_shape_cfg.ke = 2.0e3
    articulation_builder.default_shape_cfg.kd = 1.0e2
    articulation_builder.default_shape_cfg.kf = 1.0e3
    articulation_builder.default_shape_cfg.mu = 0.75
    articulation_builder.add_usd(
        asset_file,
        collapse_fixed_joints=False,
        enable_self_collisions=False,
        hide_collision_shapes=True,
    )
    builder = newton.ModelBuilder(up_axis=newton.Axis.Z)
    builder.request_state_attributes("body_parent_f")
    builder.request_contact_attributes("force")
    builder.add_world(articulation_builder)
    builder.default_shape_cfg.margin = 0.0
    builder.default_shape_cfg.gap = 0.0
    builder.default_shape_cfg.ke = 1.0e3
    builder.default_shape_cfg.kd = 1.0e2
    builder.add_ground_plane(cfg=newton.ModelBuilder.ShapeConfig(collision_group=-1))
    model = builder.finalize()
    solver = newton.solvers.SolverXPBD(
        model,
        iterations=20,
        soft_body_relaxation=0.9,
        soft_contact_relaxation=0.9,
        joint_linear_relaxation=0.7,
        joint_angular_relaxation=0.4,
        joint_linear_compliance=0.0,
        joint_angular_compliance=0.0,
        rigid_contact_relaxation=0.8,
        rigid_contact_con_weighting=True,
        angular_damping=0.0,
        enable_restitution=False,
    )
    # metrics = SolutionMetricsNewton(
    #    dt=dt,
    #    model=model,
    #    sparse=False,
    # )
    # logger = SolutionMetricsLogger(
    #    metrics=metrics,
    #    max_frames=max_frames,
    #    mode=SolutionMetricsLogger.Mode.ROLLING,
    # )
    setup = SolverSetup(
        name="xpbd",
        builder=builder,
        model=model,
        solver=solver,
        # metrics=metrics,
        # logger=logger,
    )
    return setup


###
# Runtime
###


class Example:
    def __init__(self, viewer: newton.viewer.ViewerBase, args, use_graph=True, start_paused=False):
        # Set simulation run-time configurations
        self.viewer_fps = 50
        self.viewer_dt = 1.0 / self.viewer_fps
        target_sim_dt = 0.0025  # 400 fps
        # target_sim_dt = 0.001 # 1000 fps
        self.sim_substeps = max(1, round(self.viewer_dt / target_sim_dt))
        self.sim_dt = self.viewer_dt / self.sim_substeps
        msg.notif(f"Using sim_dt = {self.sim_dt} ({self.sim_substeps} substeps per frame)")
        self.sim_time = 0.0
        self.viewer = viewer
        self.args = args
        self.device = wp.get_device()
        self.use_graph = use_graph
        self.start_paused = start_paused

        self.record_traj = False
        if self.record_traj:
            self.frame_id = 0
            self.num_recording_frames = int(np.floor(RECORD_END_TIME / self.viewer_dt)) + 1
            self.traj_body_q = np.zeros((self.num_recording_frames, 4, 7))
            self.traj_body_dq = np.zeros((self.num_recording_frames, 4, 6))
            fps = int(round(1 / target_sim_dt))
            self.recording_folder = os.path.join(get_examples_output_path(), "four_bar", f"{fps} fps")
            os.makedirs(self.recording_folder, exist_ok=True)

        # Clip recording state
        self.record_clips = bool(getattr(args, "record", None))
        if getattr(args, "record", None):
            self.video_target_frames = int(np.floor(RECORD_END_TIME / self.viewer_dt)) + 1

        # External forces: applied in viewer vs automatically (currently none)
        self.viewer_forces = True

        # Define the asset file
        assets_dir = os.path.join(get_kamino_assets_directory(), "validation")
        asset_file = os.path.join(assets_dir, "four_bar_articulated.usda")

        # Create the solver setups
        self.setup_kamino_soft = make_setup_solver_kamino(asset_file, self.sim_dt, 5000, 0.01)
        self.setup_kamino_stiff = make_setup_solver_kamino(asset_file, self.sim_dt, 5000, 0.1)
        self.setup_mujoco_soft = make_setup_solver_mujoco(asset_file, self.sim_dt, 5000, 0.1)
        self.setup_mujoco_medium = make_setup_solver_mujoco(asset_file, self.sim_dt, 5000, 0.01)
        self.setup_mujoco_stiff = make_setup_solver_mujoco(asset_file, self.sim_dt, 5000, 0.001)
        self.setup_xpbd = make_setup_solver_xpbd(asset_file, self.sim_dt, 5000)

        # Solver setup choice
        self.setup_names = ["Kamino_soft", "Kamino_stiff", "MuJoCo_soft", "MuJoCo_medium", "MuJoCo_stiff", "XPBD"]
        self.setups = [
            self.setup_kamino_soft,
            self.setup_kamino_stiff,
            self.setup_mujoco_soft,
            self.setup_mujoco_medium,
            self.setup_mujoco_stiff,
            self.setup_xpbd,
        ]
        self.current_setup_id = 0
        self.init_setup(reset_viewer=True, first=True)

    @property
    def setup(self):
        return self.setups[self.current_setup_id]

    def capture(self):
        self.graph = None
        if self.device.is_cuda:
            with wp.ScopedCapture() as capture:
                self.simulate()
            self.graph = capture.graph

    def reset(self):
        if self.record_traj:
            self.frame_id = 0
        self.setup.reset()

    def start_recording_clip(self):
        """Start a new video clip for the currently active solver."""
        if not hasattr(self.viewer, "start_clip"):
            msg.warning("Recording is not enabled (pass --record sync|async at launch).")
            return
        solver_name = self.setup_names[self.current_setup_id]
        fps = int(round(1 / self.sim_dt))
        self.viewer.start_clip(
            output_path=os.path.join(self.args.video_base_dir, f"{fps} fps", f"recording_{solver_name}.mp4"),
            max_frames=self.video_target_frames,
            video_folder=os.path.join(self.args.video_base_dir, f"{fps} fps", f"frames_{solver_name}"),
            fps=self.viewer_fps,
            keep_frames=self.args.keep_frames,
        )

    def init_setup(self, reset_viewer=True, first=False):
        msg.notif(f"Initializing {self.setup_names[self.current_setup_id]} solver")
        # Reset state
        self.reset()

        # Set model in viewer
        if reset_viewer:
            self.viewer.set_model(self.setup.model)
            self.viewer._paused = self.start_paused  # Start paused to inspect the initial configuration
            if hasattr(self.viewer, "set_camera"):  # Set initial camera on viewer
                camera_pos = wp.vec3(0.02, -0.2, 0.13)
                pitch = -15.0
                yaw = 90.0
                self.viewer.set_camera(camera_pos, pitch, yaw)
                self.viewer.camera.sync_pivot_to_view(distance=0.2)  # Default pivot distance is 5m
            self.viewer.show_contacts = True
            self.viewer.vsync = True
        if reset_viewer and not first and hasattr(self.viewer, "register_ui_callback"):
            # We skip GUI registration on first call as it is done in newton.examples.run() automatically
            self.viewer.register_ui_callback(lambda ui, ex=self: ex.gui(ui), position="side")

        # Reset graph
        self.graph = None

        # Warm-up simulation
        self.setup.step(self.setup.state_0, self.sim_dt)
        self.reset()

        # Capture graph again
        if self.use_graph:
            self.capture()

    # simulate() performs one frame's worth of updates
    def simulate(self):
        for _ in range(self.sim_substeps):
            # Clear and apply forces to the solver state
            self.setup.state_0.clear_forces()
            if self.viewer_forces:
                self.viewer.apply_forces(self.setup.state_0)

            # Step solver
            self.setup.step(self.setup.state_0, self.sim_dt)

            # Swap the leading solver state
            self.setup.state_0, self.setup.state_1 = self.setup.state_1, self.setup.state_0

    def step(self):
        if self.record_traj:
            if self.frame_id < self.num_recording_frames:
                self.traj_body_q[self.frame_id] = self.setup.state_0.body_q.numpy()
                self.traj_body_dq[self.frame_id] = self.setup.state_0.body_qd.numpy()
                self.frame_id += 1
                if self.frame_id == self.num_recording_frames:
                    solver_name = self.setup_names[self.current_setup_id]
                    model = self.setup.model
                    np.save(os.path.join(self.recording_folder, "body_mass.npy"), model.body_mass.numpy())
                    np.save(os.path.join(self.recording_folder, "body_CoM.npy"), model.body_com.numpy())
                    np.save(os.path.join(self.recording_folder, "body_inertia.npy"), model.body_inertia.numpy())
                    np.save(os.path.join(self.recording_folder, "joint_X_p.npy"), model.joint_X_p.numpy())
                    np.save(os.path.join(self.recording_folder, "joint_X_c.npy"), model.joint_X_c.numpy())
                    np.save(os.path.join(self.recording_folder, "joint_id_p.npy"), model.joint_parent.numpy())
                    np.save(os.path.join(self.recording_folder, "joint_id_c.npy"), model.joint_child.numpy())
                    np.save(os.path.join(self.recording_folder, f"traj_body_q_{solver_name}.npy"), self.traj_body_q)
                    np.save(os.path.join(self.recording_folder, f"traj_body_dq_{solver_name}.npy"), self.traj_body_dq)
                    msg.notif("Trajectory recorded")
        if self.graph:
            wp.capture_launch(self.graph)
        else:
            self.simulate()
        self.sim_time += self.viewer_dt

    def render(self):
        self.viewer.begin_frame(self.sim_time)
        self.setup.render(self.viewer)
        self.viewer.end_frame()

    @staticmethod
    def create_parser():
        return newton.examples.create_parser()

    def gui(self, imgui):
        # Checkbox to toggle force input (applied in viewer, or automatic force ramp-up)
        clicked, self.viewer_forces = imgui.checkbox("User-applied forces", self.viewer_forces)
        if clicked:
            self.init_setup(reset_viewer=False)

        # Toggle for solver backend
        imgui.text("Solver backend")
        if imgui.begin_combo("##solver_combo", self.setup_names[self.current_setup_id]):
            for solver_id, solver_name in enumerate(self.setup_names):
                selected = solver_id == self.current_setup_id
                clicked, _ = imgui.selectable(solver_name, selected)
                if clicked:
                    self.current_setup_id = solver_id
                    self.init_setup(reset_viewer=True)
                if selected:
                    imgui.set_item_default_focus()
            imgui.end_combo()

        # Checkbox to record a clip on the next Reset press
        if getattr(self.args, "record", None) and hasattr(self.viewer, "start_clip"):
            _, self.record_clips = imgui.checkbox("Record clip on Reset", self.record_clips)

        # Reset button (using the solver-internal reset, rather than fully reloading the example and GUI)
        if imgui.button("Reset##custom_reset"):
            self.reset()
            if self.record_clips and hasattr(self.viewer, "start_clip"):
                self.start_recording_clip()


if __name__ == "__main__":
    parser = Example.create_parser()
    parser.add_argument(
        "--record",
        type=str,
        choices=["sync", "async"],
        default="async",
        help="Enable frame recording: 'sync' for synchronous, 'async' for non-blocking",
    )
    parser.add_argument(
        "--video-output",
        type=str,
        default=None,
        help="Output MP4 path (defaults to <examples_output>/four_bar/recording.mp4)",
    )
    parser.add_argument(
        "--keep-frames",
        type=bool,
        default=True,
        help="Keep recorded PNG frames after the MP4 has been generated",
    )
    viewer, args = newton.examples.init(parser)

    recording_dir = os.path.join(get_examples_output_path(), "four_bar")
    args.video_base_dir = recording_dir
    if args.record:
        viewer = enable_recording(
            viewer,
            record_video=True,
            video_folder=os.path.join(recording_dir, "frames"),
            async_save=(args.record == "async"),
        )

    example = Example(viewer, args, use_graph=True, start_paused=False)

    newton.examples.run(example, args)
